name: Continous Build

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Pesde
              uses: lumin-org/setup-pesde@v0.3.2
              with:
                cache: true

            - name: Install Packages
              run: pesde install

            - name: Build
              run: rojo build build.project.json --output ./ui-components.rbxm

            - name: Get Timestamp
              id: date
              run: echo "::set-output name=current_datetime::$(date +'%Y-%m-%d %H:%M:%S')"

            - name: Release
              uses: softprops/action-gh-release@v2.2.1
              with:
                tag_name: Continous Build
                name: Continous Build
                prerelease: true
                generate_release_notes: true
                body: |
                  Build created at ${{ steps.date.outputs.current_date }}
                  Latest commit: ${{ github.sha }}
                files: |
                 ./ui-components.rbxm